// Generated by CoffeeScript 1.6.3
(function() {
  var Json, Loader,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Loader = require('./Loader');

  Json = (function(_super) {
    __extends(Json, _super);

    Json.prototype.directory = '/app/lang';

    function Json(directory) {
      this.directory = directory != null ? directory : this.directory;
    }

    Json.prototype.load = function(parent, name, language) {
      var data, e, path;
      path = this.getFileSystemPath(parent, name, language);
      try {
        data = require(path);
      } catch (_error) {
        e = _error;
        data = {};
      }
      return data;
    };

    Json.prototype.getFileSystemPath = function(parent, name, language) {
      return this.directory + (parent !== '' ? '/' + parent : '') + ("/" + language + "." + name + ".json");
    };

    return Json;

  })(Loader);

  module.exports = Json;

}).call(this);
