// Generated by CoffeeScript 1.6.3
(function() {
  var Loader;

  Loader = (function() {
    function Loader() {}

    Loader.prototype.load = function() {
      throw new Error('Translator loader: you have to implement method load.');
    };

    Loader.prototype.getFileSystemPath = function() {
      throw new Error('Translator loader: you have to implement method getFileSystemPath.');
    };

    return Loader;

  })();

  module.exports = Loader;

}).call(this);
